server:
  port: 8080
spring:
  application:
    name: "quizify"
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_db
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    sql:
      init:
        mode: always
#    hibernate:
#      ddl-auto: update



